# Generated by Django 3.1.2 on 2020-10-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarW', '0002_slidergaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
