# Generated by Django 3.1.2 on 2020-10-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarW', '0003_misionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
