# Generated by Django 3.1.2 on 2020-10-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCarW', '0004_insumos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='ident',
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
